Support SIP DTMF data messages
livekit/client-sdk-js pull request #1130
Opened 2024-05-07 11:06 UTC by dennwc

Added support for SIP DTMF data messages on rooms and participants.

For consistency with other SDKs, the `RTCEngine` data packet handler signature was changed to receive all message types, which is then switched by type in the Room.

Also compatibility code was added to properly select participant from a shared `participant_identity` on the `DataPacket` (see https://github.com/livekit/protocol/pull/706).

2024-05-07 11:23 UTC, lukasIO requested changes

2024-05-07 11:23 UTC, lukasIO commented on src/room/Room.ts
> +  private handleDataPacketAny = (packet: DataPacket) => {
nit: can we rename this to `handleDataPacket` and the current `handleDataPacket` to `handleUserPacket` ?

2024-05-07 11:23 UTC, lukasIO commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
nice! 
just to make it a bit easier to maintain, can we extract the compatibility stuff into a function? 
it seems the pattern is always `dp[myProperty] || dp.value.value[myProperty]` (empty strings are falsy in JS). Not sure if it's still elegant with typescript stuff, but having it extracted into a helper of some sort (not necessarily the one I proposed) would be nice!

2024-05-08 07:53 UTC, lukasIO commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
> But in general, sure! I assume empty arrays are falsy too, right?

no, empty arrays are truthy :D my naive proposal won't work for both strings and arrays...

2024-05-17 14:01 UTC, dennwc commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
I added the helper functions you mentioned, but I get some TS error about `DataPacket` type not supporting indexing. I might need your help on this one.

2024-05-17 15:34 UTC, lukasIO commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
I had a look and my initial idea might be totally flawed. I don't really see a way to get around the typescript issues without either being overly specific about the allowed strings or converting the protobuf to JSON first and then parsing it back. Which seems pointless and not at all simplifying things. 
While verbose, your original implementation of handling these separately looks a lot preferable to me than back and forth parsing. 
I think the main reason why I pushed for that was because we had logic duplication for transcription and user packet, but it seems that is no longer the case, because the field got renamed for transcriptions to `transcribed_participant`. So I don't see a huge incentive anymore to change what you had originally.

I pushed to a branch what would work, but that's basically just extracting what you had previously already into a function 🤦 https://github.com/livekit/client-sdk-js/commit/42b8381cecabf2c32ab8c93ee1f0a317f769d44b
Feel free to ignore it entirely.

2024-05-17 15:44 UTC, dennwc commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
Yeah, that looks very specific. OK, lets settle on the middle ground - I'll revert the "generic" part of the change, but will keep compat logic in a separate function, so that it's easier to read the main handler function.

2024-05-17 15:51 UTC, dennwc commented on src/room/RTCEngine.ts
> +          if (dp.participantIdentity === '' && dp.value.value.participantIdentity !== '') {
Done, pushed the updated function. Also simplified logic a bit.

2024-05-17 16:43 UTC, lukasIO approved these changes
nice!

2024-05-17 18:58 UTC, merged