Support track level stereo and red setting
livekit/client-sdk-js pull request #470
Opened 2022-10-14 07:33 UTC by cnderrauber

2022-10-14 07:36 UTC, cnderrauber commented
Fix https://github.com/livekit/livekit/issues/970

2022-10-14 07:39 UTC, boks1971 commented on src/room/PCTransport.ts
> +          if (fmtp.config.includes('sprop-stereo=1')) {
Does `server` have to send this?

2022-10-14 07:39 UTC, boks1971 commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
This and above is already checking for not true and setting to false. Should the check be `if set to true, override it with false when stereo`?

2022-10-14 07:42 UTC, boks1971 commented on src/room/PCTransport.ts
> +          fmtp.config += ';stereo=1';
Should this check if config already has `stereo=1` and add only if not there? i. e. will multiple pass through here keep adding `stereo=1`? Guess it probably does not affect functionality, but the SDP could look strange.

2022-10-14 07:42 UTC, cnderrauber commented on src/room/PCTransport.ts
> +          if (fmtp.config.includes('sprop-stereo=1')) {
yeah, it should have it if sending a stereo track

2022-10-14 07:47 UTC, cnderrauber commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
the red and dtx can be left to undefined, means use `default` values. So this only disable them if dtx and red not enabled explicitly

2022-10-14 07:52 UTC, cnderrauber commented on src/room/PCTransport.ts
> +          fmtp.config += ';stereo=1';
Test it will not be added repeatedly in chrome, but the check is safe for various browsers, will add it

2022-10-14 07:57 UTC, boks1971 approved these changes

2022-10-14 15:03 UTC, lukasIO commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
should this logic maybe live in `publishTrack` instead of `setTrackEnabled` ? 
If users choose to use the `publishTrack` API directly, I guess they would have to handle all this by themselves otherwise?

2022-10-15 00:53 UTC, davidzhao requested changes

2022-10-15 00:53 UTC, davidzhao commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
yeah I agree this should be in publishTrack.

why do we need to set dtx or red to default false? It seems that we shouldn't change the default behavior of other unrelated params.

also, the logic would be easier to read with the `??` operator

```
publishOptions ??= {};
publishOptions.red ??= false
publishOptions.dtx ??= true
```

2022-10-15 00:53 UTC, davidzhao commented on src/room/participant/LocalParticipant.ts
> +            if ('channelCount' in options) {
when this is moved to publishTrack, determine the actual channelCount will be a challenge. we could take in a `stereo?: boolean` parameter in publishOptions too, to give user control in case we cannot detect correctly.

In Safari, we could get channelCount from [MediaStreamTrack.getSettings()](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/channelCount). but Chrome doesn't seem to support that.. which means we may have to go look for it in the constraints.

2022-10-15 07:55 UTC, lukasIO commented on src/room/participant/LocalParticipant.ts
> +            if ('channelCount' in options) {
it's also not fully fail proof but chrome should support `getConstraints()` that would return the channel count in case it was manually set.

2022-10-17 01:57 UTC, cnderrauber commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
@lukasIO sounds good, will move it there.
@davidzhao For stereo audio tracks, it will use high bitrates encoding (128kbps or higher) and most scenario is music, RED will cost more bandwidth and DTX might cause noise in special case or device.

2022-10-17 02:51 UTC, cnderrauber commented on src/room/participant/LocalParticipant.ts
> +                publishOptions.dtx = false;
solved by https://github.com/livekit/client-sdk-js/pull/470/commits/9b8a0a4dd1127ee88fd481fd3343f6af2218589f

2022-10-17 09:46 UTC, lukasIO approved these changes

2022-10-17 19:03 UTC, davidzhao reviewed
looks good! remaining question about defaults

2022-10-17 19:18 UTC, bekriebel commented on src/room/participant/LocalParticipant.ts
> +      options.red ??= false;
I haven't had the chance to catch up on this whole thread, but I'm excited to test it out later this week!

Regarding red support, I will say that from my testing - high bitrate stereo + red (with DTX, noise canceling, echo canceling, etc. all turned off), audio sounds AMAZING. Using similar bitrates with opus by itself doesn't sound nearly as good. For my "quality audio mode" I plan to leave red enabled.

2022-10-17 19:26 UTC, davidzhao commented on src/room/participant/LocalParticipant.ts
> +      options.red ??= false;
thanks for the feedback @bekriebel ! that's wonderful to hear it made a significant difference in audio quality.

2022-10-18 01:36 UTC, cnderrauber commented on src/room/participant/LocalParticipant.ts
> +      options.red ??= false;
It is hard to reproduce, but a few users report noise with special music cases before, and we close DTX to fix it. At least, opus decoder will generate `comfort noise` when received dtx packet, that is no needed and might harm to quality in music case. So I suggest disable dtx in stereo mode

2022-10-18 07:43 UTC, davidzhao approved these changes
lg!

2022-10-18 08:22 UTC, merged